In [21]:
import yfinance as yf
import pandas as pd


# Define the ticker symbol and the start and end dates
ticker = "TSLA"

# Get data on this ticker
tickerData = yf.Ticker(ticker)
# tickerData.info

# Get the historical prices for this ticker
tickerDf = tickerData.history(period="1d", start="2010-5-31", end="2020-5-31")

# last closing price
tickerDf["Close"].iloc[-1]

tickerDf.head()
print(tickerDf.shape)

# tickerDf.to_csv("apple.csv")  # Save it to a CSV file

(2497, 7)

In [34]:
import pandas as pd
import yfinance as yf
import datetime as dt 
from datetime import timedelta

today =  dt.datetime.now()
d1 = today.strftime("%Y-%m-%d") # get the date in string format
d1
d2 = (today - timedelta(days=365)).strftime("%Y-%m-%d") # get the date in string format from one year ago
d2

start_date = d2
end_date = d1

ticker = "PAK"

# Get data on this ticker
tickerData = yf.Ticker(ticker)
# tickerData.info

# Get the historical prices for this ticker
tickerDf = tickerData.history(period="1d", start=start_date, end=end_date)

# last closing price
# tickerDf["Close"].iloc[-1]

tickerDf.head()

# tickerDf.to_csv("apple.csv")  # Save it to a CSV file

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-02-28 00:00:00-05:00,210.589996,211.229996,203.750000,205.710007,153144900,0.0,0.0
2023-03-01 00:00:00-05:00,206.210007,207.199997,198.520004,202.770004,156852800,0.0,0.0
2023-03-02 00:00:00-05:00,186.740005,193.750000,186.009995,190.899994,181500700,0.0,0.0
2023-03-03 00:00:00-05:00,194.800003,200.479996,192.880005,197.789993,154193300,0.0,0.0
2023-03-06 00:00:00-05:00,198.539993,198.600006,192.300003,193.809998,128100100,0.0,0.0

In [5]:
# pakistan stock data 
import pandas as pd
import yfinance as yf
import datetime as dt
from datetime import timedelta

today =  dt.datetime.now()
d1 = today.strftime("%Y-%m-%d") # get the date in string format
d1
d2 = (today - timedelta(days=365)).strftime("%Y-%m-%d") # get the date in string format from one year ago
d2

start_date = d2
end_date = d1

start_date = d2
end_date = d1

ticker = "META"

# Get data on this ticker
tickerData = yf.Ticker(ticker)
# tickerData.info

# Get the historical prices for this ticker
tickerDf = tickerData.history(period="1y", start=start_date, end=end_date)

# last closing price
# tickerDf["Close"].iloc[-1]

tickerDf.head()

tickerDf.to_csv("META.csv")  # Save it to a CSV file

In [2]:
tickerDf.shape

(251, 8)